### ISSUE TITLE
Thirdparty/MemoryPool  File 

### ISSUE THREAD

**Issue by myjndyfjl** [FSMargoo/RCEngine#1]
#include "thirdparty/MemoryPool/C-11/MemoryPool.h"
![image](https://github.com/user-attachments/assets/8a5da783-115b-4b35-9482-c54df817cee9)

**Comment by FSMargoo** [comment]
请您详细描述一下你遇到的问题，我并不理解您的意思。
如果你想说的是该模块无法正常加载，请使用
```
 git clone --recurse-submodules https://github.com/FSMargoo/RCEngine/RCEngine.git 
```
克隆本仓库，这样将可以正常拉取 submodule 模块。
